source = ~/.config/hypr/colors.conf

background {
    monitor =
    path = $HOME/.config/hypr/wallpapers/mountains.png
    blur_passes = 3
    blur_size = 8
    color = $background
}

input-field {
    monitor =
    size = 260, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = $foreground
    inner_color = $surface
    font_color = $foreground
    fade_on_empty = false
    placeholder_text = <span foreground="##ffffff">Password...</span>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $foreground
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = $muted
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 70
    halign = center
    valign = center
}
