#!/usr/bin/env bash
# Called by quickshell/MonitorManager.qml (SUPER+M) with the full monitor
# layout as a single argument (one "monitor=..." line per connected
# monitor, newline-separated). Writes it to hypr/monitors.conf - sourced
# from hyprland.conf, so it persists across reboots - and applies every
# line immediately via `hyprctl keyword monitor` so you see it live
# without needing to reload or re-login.
set -euo pipefail

CONF="$HOME/.config/hypr/monitors.conf"
content="${1:-}"

if [[ -z "$content" ]]; then
    echo "usage: apply-monitor-layout.sh '<monitor=... lines>'" >&2
    exit 1
fi

{
    echo "# Generated by the Quickshell Monitor Manager (SUPER+M)."
    echo "# This file is fully rewritten each time you use that tool - if"
    echo "# you'd rather hand-edit monitor rules yourself, do it here, but"
    echo "# expect the tool to overwrite them next time it's used to apply."
    printf '%s\n' "$content"
} > "$CONF"

while IFS= read -r line; do
    [[ "$line" =~ ^monitor= ]] || continue
    spec="${line#monitor=}"
    hyprctl keyword monitor "$spec" >/dev/null 2>&1 || true
done <<< "$content"

notify-send "Monitors" "Layout applied" 2>/dev/null || true
